version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsportal
      - JWT_SECRET=change_this_to_a_long_secret
      - SETUP_TOKEN=use_a_one_time_token_here
      - USE_S3=false
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - backend

volumes:
  mongo-data:

